### ISSUE TITLE
Is the remove unused translations function still available for Mac?

### ISSUE THREAD

**Issue by donatellijl** [JoacimWall/Visual-studio-multilingual-extension#11]
I right click my master file and I don't see the option to remove unused translations. Is this feature still available?

**Comment by JoacimWall** [comment]
Hello
since vs2022, I haven't had time to port this function. but it's in my backlog.
if you still have vs 2019 you can install version 1.0.3 and run the function in that environment.

//Joacim

**Comment by JoacimWall** [comment]
> I right click my master file and I don't see the option to remove unused translations. Is this feature still available?

Hi this is now fixed in the latest version for Mac. 
Sorry for the delay.

//Joacim
