### ISSUE TITLE
Issues Translating Czech 

### ISSUE THREAD

**Issue by ajvanlaningham** [JoacimWall/Visual-studio-multilingual-extension#12]
I'm having an issue with translating an AppResources.cz.resx file. 

It shifts all "New" statuses to "Need Review" but does not actually perform any of the translations. 

![Screenshot 2024-02-14 at 10 00 31 AM](https://github.com/JoacimWall/Visual-studio-multilingual-extension/assets/77026821/de9de542-ed2f-4ebc-83da-3261960a272b)

**Comment by JoacimWall** [comment]
> 
Hi has you right clicked and selected Translate in the popup menu? 
<img width="416" alt="image" src="https://github.com/JoacimWall/Visual-studio-multilingual-extension/assets/9278908/d668cbe5-ea31-4016-b945-f854aaba9200">
//Joacim

**Comment by ajvanlaningham** [comment]
Yes, I followed the steps to translate exactly. I use this multilingual extension extensively and followed all the steps I normally follow when translating. In fact, the multilingual extension translated an identical resx file to Slovak for me just this morning.

**Comment by JoacimWall** [comment]
Can provide me with the AppResources.resx and the AppResources.cz.resx so can I debug it.

**Comment by ajvanlaningham** [comment]
Sent to the email you have listed on your github. Thank you in advance

**Comment by JoacimWall** [comment]
I also add the solution he for knowledge if someone get the same issue.
When the Google translate can't recognize the language to translate to it will return same as input language. You have specified  .cz.resx "cz" that is not correct it should be cs.resx or cs-CZ.resx
<img width="375" alt="image" src="https://github.com/JoacimWall/Visual-studio-multilingual-extension/assets/9278908/956a8451-08c4-40ec-8d89-788c49897b38">

//Joacim
