### ISSUE TITLE
UWP and RESW support

### ISSUE THREAD

**Issue by Japollack** [JoacimWall/Visual-studio-multilingual-extension#2]
In UWP _.resx_ is renamed to _.resw_ (default location: _\Strings\en-US\Resources.resw_) which AFAIK includes/supports/accepts only 'strings' and file paths:
[https://softwareengineering.stackexchange.com/questions/236741/why-did-microsoft-dropped-the-resx-model-for-resw-in-windows-store-applications](https://softwareengineering.stackexchange.com/questions/236741/why-did-microsoft-dropped-the-resx-model-for-resw-in-windows-store-applications)

Could this extension natively support and accept RESW files?

More about localising strings in UWP
[https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest](https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest)

**Comment by JoacimWall** [comment]
Hi @Japollack
Thank you for your mail. 
I have now added resw support to the windows version of the extension.
Regards Joacim

**Comment by JoacimWall** [comment]
Request Implemented

**Comment by JoacimWall** [comment]
Now also the mac version suport resw files.

**Comment by Japollack** [comment]
> Request Implemented

Thank you for implementing it. That was quick! I will check it out.
