### ISSUE TITLE
Unable to install - Xamarin.FormsPreviewer required

### ISSUE THREAD

**Issue by donatellijl** [JoacimWall/Visual-studio-multilingual-extension#3]
I am getting an error that Xamarin.FormsPreviewer is required, but it has been deprecated since Visual Studio for Mac version 8.8. I am currently on Visual Studio for Mac version 8.9.1. Can this extension be upgraded for version 8.9?

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=macos 

![Screen Shot 2021-03-10 at 3 15 41 PM](https://user-images.githubusercontent.com/45564887/110691713-7c54e680-81b3-11eb-945f-cfd47589cf3b.png)

**Comment by JoacimWall** [comment]
Hi I was not able to reproduce your error but I have build a new version 1.26 that are compiled with visual studio 8.9.1 that you  can try out. For you information I have no referens to Xamarin.FormsPreviewer so I don't see why you get the error.

Could it be that you are trying to install this add-in

https://docs.telerik.com/devtools/xamarin/installation-and-deployment/mac/project-wizard



//regards Joacim

**Comment by donatellijl** [comment]
Ahh, yes. I tried installing another extension and got the same issue. The "add-in ProjectTemplateXamarin...could not be updated..." message was actually just a warning that was showing because I had a Telerik extension that was no longer compatible with my version of Visual Studio. I didn't realize when you installed an extension, VS checked all the other extensions you had installed. Removing the Telerik extension got rid of this warning. Thank you for pointing me in the right direction!
