### ISSUE TITLE
Support for language only resx files

### ISSUE THREAD

**Issue by donatellijl** [JoacimWall/Visual-studio-multilingual-extension#4]
Here is the current AppResources structure in my app:
![Screen Shot 2021-03-11 at 9 06 05 AM](https://user-images.githubusercontent.com/45564887/110799293-04390000-8249-11eb-92dc-f1d8e6b606ee.png)

I only use the language code in the file name in some cases. I have them set up like this to prevent duplicate strings that would need to be checked by a stakeholder. For example, I may have a user in The Netherlands or in Belgium that speaks Dutch. Mostly all the text is the same for these two users, except if the user is in Belgium, then there are a few strings that need modified. According to the documentation, the app chooses the right file for the resource key in order of specificity.

![Screen Shot 2021-03-11 at 9 13 40 AM](https://user-images.githubusercontent.com/45564887/110800338-15ced780-824a-11eb-9be5-78bf4457eae8.png)
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?pivots=macos#test-localization 

There is a requirement for this extension that the files have both the language and the region in the AppResources file name, which my files obviously don't meet. Would you consider changing the requirement to have just the language specified, instead of the whole culture?

**Comment by JoacimWall** [comment]
Hi I will add it to my backlog.

//joacim

**Comment by JoacimWall** [comment]
Hi There is a new version 1.0.27 that should suport your request (Mac OS version). Not implemented yet in Windows version.  In your sample above when you right click the master file and select sync or translate it will only effect the .fr.resx and .nl.resx file. 

Please try it out and comment her if it's ok or if something missing.

//Regards Joacim

**Comment by donatellijl** [comment]
Hi I tried this out and it worked as you said. It only synced and translated the the fr.resx and nl.resx. Thanks!
