### ISSUE TITLE
Export all to excel regardless of status

### ISSUE THREAD

**Issue by donatellijl** [JoacimWall/Visual-studio-multilingual-extension#5]
Hi, I would like to export all of the translations to excel regardless of their status. My stakeholders like to see all the translations so they can reference them when they are finalizing new translations. They can easily use the filter function in excel to exclude the final translations if they don't want to see them.  Could this be an option to set in the extensions settings?

Great extension by the way, this has very much streamlined our translation process already!

**Comment by JoacimWall** [comment]
I put it in to the backlog

**Comment by JoacimWall** [comment]
This is now implemented in the 1.0.29 version.

**Comment by donatellijl** [comment]
Yay this is great!! Thanks! :)
