### ISSUE TITLE
No translation status not working

### ISSUE THREAD

**Issue by donatellijl** [JoacimWall/Visual-studio-multilingual-extension#6]
I have a few strings that I want to have no translation. I put 'No translation' as the comment for those strings in the main AppResources.resx. Whenever I right click AppResources.resx and choose 'Sync all language files with this', it changes the status in the AppResources.resx from 'No translation' to 'Need review' and adds them to the translated files. I am on version 1.0.29.

**Comment by JoacimWall** [comment]
Now it should be fixed in version 1.0.30

//Joacim

**Comment by donatellijl** [comment]
Yep, it's fixed in 1.0.30. Thanks!
