### ISSUE TITLE
Advise please, Translations have stopped synchronising

### ISSUE THREAD

**Issue by TechGuyGeek** [JoacimWall/Visual-studio-multilingual-extension#7]
So for the last couple of weeks my Translations have stopped synchronising, I have uninstalled and re installed and tested both on windows and apple but nothing I have 35 resx files with 260 rows all following the lower case upper case letters and then the master file it all did work and then just a couple of weeks ago just stopped, im assuming this is just me as no one else seems to have the issue :(   is there anyway to find out where the issue is, perhaps a log file? I have tried rolling back a month or 2 on my translations but this did not fix the issue.

**Comment by JoacimWall** [comment]
test to open the files in a xml viewer to validate that the files are correct formated. Start with the master file. 
If this not solve you can email me the resx files so can I debug to se what is not working. 

Regards Joacim

**Comment by TechGuyGeek** [comment]
Thanks for the tip, Unfortunately I am not receiving any error in the XML editor but managed to resolve the issue by manually generating the xml for each language and then just auto translated from there. i will keep an eye out and let you know if i ever find the issue
