### ISSUE TITLE
Unable to export base AppResources.resx file to excel

### ISSUE THREAD

**Issue by donatellijl** [JoacimWall/Visual-studio-multilingual-extension#8]
Hello! I used to be able to export the base AppResources.resx to excel along with the translated versions. Was this feature removed?

**Comment by JoacimWall** [comment]
Hi 
There is a new version for Mac/windows that this is now fixed in. 
you need to turn this on by setting "ExportMasterFileOnExport": true in the MultiLingualExtensionSettings.json file that is created the first time you run any function from the extension. 

//Joacim
