### ISSUE TITLE
Dependency Issue Installing v2.06 on Mac

### ISSUE THREAD

**Issue by donatellijl** [JoacimWall/Visual-studio-multilingual-extension#9]
Hi, I tried to install the latest version for Mac, but I'm getting an error.

On VS 2019, I'm getting an error that there are missing dependencies. 
<img width="316" alt="Screen Shot 2022-10-10 at 8 24 00 AM" src="https://user-images.githubusercontent.com/45564887/194865604-030b62f9-603c-480e-a8b8-858a619273ea.png">

On VS 2022, The package is not in the enabled state after restarting. I tried to enable and disable it, but it remains in the disabled state. I didn't receive any errors about dependencies.

Any ideas?

Thanks!

**Comment by JoacimWall** [comment]
Hi 

For VS2019 a recommend version 1.0.30

I am not using VS2019 anymore so I can’t test on that one. For VS2022 I’t works for me. Try to uninstall and install version 2.0.6.  

The differs from version 2.0.2 > 2.0.6 
1. When you had a text with a ”." like this "Hello. Test”  it only translate Hello
2. Added a json MultilingualExtensionSettings.json so you can configure some properties. 

//Thanks Joacim

**Comment by donatellijl** [comment]
Ok, makes sense for VS 2019. I tried uninstalling 2.0.6 on VS 2022 and reinstalling it and I'm still seeing it shown as 'disabled' after installation. If I install 2.0.2 it shows as 'installed' after installation.

![Screen Shot 2022-10-10 at 9 25 00 AM](https://user-images.githubusercontent.com/45564887/194877518-6b9b8dd3-a6b3-40a1-aa31-38c8cf5e33f3.png)

![Screen Shot 2022-10-10 at 9 25 23 AM](https://user-images.githubusercontent.com/45564887/194877550-5de19ec4-206c-47a1-a002-bfd37ab95965.png)

![Screen Shot 2022-10-10 at 9 25 33 AM](https://user-images.githubusercontent.com/45564887/194877527-2090ea1c-af83-494c-b68f-e451301157f1.png)

Even after restarting VS 2022, I still see it as disabled.

**Comment by donatellijl** [comment]
I figured it out. I had to update VS 2022 to latest. I'm now on version 17.3.6.

**Comment by JoacimWall** [comment]
Nice that it works. In windows extension you can specify the min and max version for Visual studio. I haven't found how I do that in Mac so I think it just take the version of Visual studio that I use to build the extension with. 

//Joacim
